evaluator: QwenEvaluator

num_traj: 200
order: false
env_config:
  id: 'gym_rank/Rank-v0'
  difficulty: 1
  verify_iter: 2

model: qwen
model_path: ""
prompt_config:
  use_vision: false
  use_language: true
  enable_verification: true
  prompt_language: ["Q_Rank_L"]
  pattern_language: ["answer"]

generation_config:
  max_new_tokens: 128
output_dir: logs/qwen_rank_language/in-distribution.jsonl
